use crate::config::{Config, Mode, Site, PLAIN_PORT};
use crate::paths;
use crate::target::Target;
use std::process::Command;

/// Quote a value for the Caddyfile.
///
/// Paths and upstreams reach a config file that a **root** daemon loads, and
/// they are not trustworthy: a directory may legitimately contain `}` or a
/// quote, and config.json is writable by anything running as the user. Without
/// this, such a value terminates the site block and everything after it is
/// parsed as further top-level directives.
///
/// Control characters are dropped rather than escaped — no legitimate path or
/// address contains a newline, and keeping them only gives an attacker
/// something to work with.
fn quote(value: &str) -> String {
    let cleaned: String = value.chars().filter(|c| !c.is_control()).collect();
    let escaped = cleaned.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

/// Escape text for the generated offline page.
///
/// That page is served from `https://<site>`, so anything injected here runs
/// on the site's own origin with access to its storage.
fn html_escape(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for c in value.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

/// Render the whole Caddyfile from config. The file is regenerated in full on
/// every change — there is no incremental editing to get out of sync.
pub fn render(cfg: &Config) -> String {
    let mut out = String::new();
    out.push_str("# Generated by Portico. Edits here are overwritten.\n");
    out.push_str("{\n");
    out.push_str(&format!("\tadmin {}\n", paths::CADDY_ADMIN));
    out.push_str("\tlocal_certs\n");
    // One access log for every site. `include` catches each site's generated
    // access logger, and the matching `exclude` keeps the same records from
    // being duplicated into Caddy's runtime log.
    out.push_str("\tlog default {\n");
    out.push_str("\t\texclude http.log.access\n");
    out.push_str("\t}\n");
    out.push_str("\tlog access {\n");
    out.push_str("\t\tinclude http.log.access\n");
    out.push_str(&format!(
        "\t\toutput file {} {{\n",
        quote(&paths::access_log().to_string_lossy())
    ));
    out.push_str("\t\t\troll_size 10MiB\n");
    out.push_str("\t\t\troll_keep 3\n");
    // Caddy creates log files 0600 and runs as root in System mode; without
    // this the unprivileged app could never read its own access log.
    out.push_str("\t\t\tmode 0644\n");
    out.push_str("\t\t}\n");
    out.push_str("\t\tformat json\n");
    out.push_str("\t}\n");
    if cfg.mode.is_standalone() {
        // Without root there is no port 80, so Caddy must not try to bind it
        // for its automatic HTTP->HTTPS redirects.
        out.push_str(&format!("\thttp_port {}\n", cfg.http_port()));
        out.push_str(&format!("\thttps_port {}\n", cfg.https_port()));
    }
    out.push_str("}\n\n");

    // Catch-all on the loopback listener. Without it an unmatched Host gets a
    // bare empty 200, which is baffling when it arrives down a tunnel.
    if !cfg.sites.is_empty() {
        out.push_str(&format!("http://:{PLAIN_PORT} {{\n"));
        out.push_str("\tbind 127.0.0.1\n");
        out.push_str("\trespond \"Portico: no site configured for {host}\" 404\n");
        out.push_str("}\n\n");
    }

    for site in &cfg.sites {
        // The vhost the browser talks to.
        let (scheme, port) = if site.ssl {
            ("https", cfg.https_port())
        } else {
            ("http", cfg.http_port())
        };
        out.push_str(&format!("{scheme}://{}:{port} {{\n", site.domain));
        out.push_str(&bind_line(cfg, 1));
        if site.ssl {
            out.push_str("\ttls internal\n");
        }
        out.push_str(&log_block(1));
        out.push_str(&handler_block(site, 1));
        out.push_str(&error_block(site, 1));
        out.push_str("}\n\n");

        // Loopback plain-HTTP twin that cloudflared connects to. Same handler,
        // no TLS, so the tunnel never has to trust our local CA.
        out.push_str(&format!("http://{}:{} {{\n", site.domain, PLAIN_PORT));
        out.push_str("\tbind 127.0.0.1\n");
        // Tunnelled traffic reaches us here, and should show up in the same
        // stream as local traffic rather than somewhere separate.
        out.push_str(&log_block(1));
        out.push_str(&handler_block(site, 1));
        out.push_str(&error_block(site, 1));
        out.push_str("}\n\n");
    }

    out
}

/// Enable access logging for a site. Where the records go is decided once, in
/// the global options above.
fn log_block(depth: usize) -> String {
    format!("{}log\n", "\t".repeat(depth))
}

/// A friendly page for when the thing behind a site is not running.
///
/// This is served by Caddy on a gateway error, so nothing has to hold the
/// upstream port open — the port stays free for the real app to claim.
fn error_block(site: &Site, depth: usize) -> String {
    if !matches!(site.target, Target::Proxy { .. } | Target::Node { .. }) {
        // Static and PHP sites fail as ordinary 404s, which should stay 404s.
        return String::new();
    }
    let t = "\t".repeat(depth);
    let mut s = format!("{t}handle_errors 502 503 504 {{\n");
    s.push_str(&format!("{t}\troot * {}\n", quote(&paths::offline_dir().to_string_lossy())));
    s.push_str(&format!("{t}\trewrite * /{}.html\n", site.id));
    s.push_str(&format!("{t}\tfile_server\n"));
    s.push_str(&format!("{t}}}\n"));
    s
}

/// Standalone mode binds only loopback; system mode serves the real ports.
fn bind_line(cfg: &Config, depth: usize) -> String {
    match cfg.mode {
        Mode::Standalone => format!("{}bind 127.0.0.1\n", "\t".repeat(depth)),
        Mode::System => String::new(),
    }
}

fn handler_block(site: &Site, depth: usize) -> String {
    let t = "\t".repeat(depth);
    match &site.target {
        Target::Proxy { upstream } => {
            // Caddy already forwards the original Host and sets X-Forwarded-*,
            // so a bare reverse_proxy is both correct and warning-free.
            format!("{t}reverse_proxy {}\n", quote(upstream))
        }
        Target::Node { port, .. } => format!("{t}reverse_proxy 127.0.0.1:{port}\n"),
        Target::Php { root } => {
            let mut s = format!("{t}root * {}\n", quote(root));
            s.push_str(&format!("{t}encode gzip\n"));
            // Front-controller routing: real files win, everything else goes
            // to index.php. This is what makes Laravel routes work.
            s.push_str(&format!("{t}try_files {{path}} {{path}}/ /index.php?{{query}}\n"));
            s.push_str(&format!("{t}php_fastcgi {}\n", crate::config::PHP_FPM_DEFAULT));
            s.push_str(&format!("{t}file_server\n"));
            s
        }
        Target::Dir { path } => {
            let mut s = format!("{t}root * {}\n", quote(path));
            if site.spa {
                s.push_str(&format!("{t}try_files {{path}} /index.html\n"));
            }
            s.push_str(&format!("{t}file_server\n"));
            s
        }
    }
}

/// The page shown when a site's upstream is not answering.
///
/// It refreshes itself, so the moment the real app starts listening the page
/// turns back into the app without anyone touching the browser.
fn offline_html(site: &Site) -> String {
    let (what, hint) = match &site.target {
        Target::Proxy { upstream } => (
            format!("Nothing is listening on <code>{}</code>.", html_escape(upstream)),
            "Start your app on that port. This page will refresh on its own.".to_string(),
        ),
        Target::Node { dir, command, port } => (
            // Show the project name, not an absolute path that wraps over
            // three lines; the full path stays available on hover.
            format!(
                "The dev server for <code title=\"{}\">{}</code> is not running.",
                html_escape(dir),
                html_escape(
                    &std::path::Path::new(dir)
                        .file_name()
                        .map(|n| n.to_string_lossy().into_owned())
                        .unwrap_or_else(|| dir.clone())
                )
            ),
            format!(
                "Portico can start it for you — flip <b>Run</b> on this site, or run \
                 <code>portico run {} on</code>. It will listen on port {port} and use <code>{}</code>.",
                html_escape(&site.domain),
                html_escape(command)
            ),
        ),
        _ => (
            "This site is not responding.".to_string(),
            "Check the site's target in Portico.".to_string(),
        ),
    };

    format!(
        r##"<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="refresh" content="5">
<title>{domain} is not running</title>
<style>
  :root {{ color-scheme: light dark; --fg:#16181d; --muted:#6b7280; --bg:#f6f7fb; --card:#fff; --line:#e3e6ef; --accent:#4f46e5; }}
  @media (prefers-color-scheme: dark) {{
    :root {{ --fg:#e8eaf0; --muted:#9aa1b1; --bg:#0f1116; --card:#171a21; --line:#262b36; --accent:#8b8af7; }}
  }}
  * {{ box-sizing:border-box }}
  body {{ margin:0; min-height:100vh; display:grid; place-items:center; background:var(--bg); color:var(--fg);
         font:15px/1.6 -apple-system,BlinkMacSystemFont,system-ui,sans-serif; padding:24px }}
  .card {{ max-width:560px; width:100%; background:var(--card); border:1px solid var(--line);
           border-radius:14px; padding:30px 32px; box-shadow:0 8px 30px rgba(0,0,0,.06) }}
  .dot {{ width:9px; height:9px; border-radius:50%; background:#f59e0b; display:inline-block; margin-right:9px;
          animation:pulse 1.6s ease-in-out infinite }}
  @keyframes pulse {{ 0%,100%{{opacity:1}} 50%{{opacity:.35}} }}
  h1 {{ font-size:19px; margin:0 0 6px; letter-spacing:-.01em }}
  .domain {{ font-family:ui-monospace,"SF Mono",Menlo,monospace; color:var(--accent) }}
  p {{ margin:12px 0 0; color:var(--muted) }}
  code {{ font-family:ui-monospace,"SF Mono",Menlo,monospace; background:var(--bg); border:1px solid var(--line);
          padding:1px 5px; border-radius:5px; font-size:.9em; color:var(--fg); overflow-wrap:anywhere }}
  .foot {{ margin-top:22px; padding-top:16px; border-top:1px solid var(--line); font-size:12px; color:var(--muted);
           display:flex; justify-content:space-between; align-items:baseline; gap:16px }}
  .foot span:last-child {{ white-space:nowrap }}
</style>
<div class="card">
  <h1><span class="dot"></span><span class="domain">{domain}</span> is not responding</h1>
  <p>{what}</p>
  <p>{hint}</p>
  <div class="foot">
    <span>The domain and its certificate are still set up — only the app behind it is down.</span>
    <span>Retrying every 5s</span>
  </div>
</div>
"##,
        domain = html_escape(&site.domain),
    )
}

/// Write the Caddyfile plus the generated offline pages it refers to.
pub fn write_config(cfg: &Config) -> anyhow::Result<()> {
    paths::ensure_dirs()?;
    std::fs::create_dir_all(paths::offline_dir())?;
    std::fs::write(paths::caddyfile(), render(cfg))?;

    for site in &cfg.sites {
        std::fs::write(paths::offline_page(&site.id), offline_html(site))?;
    }
    Ok(())
}

/// Write the Caddyfile and hot-reload the running daemon through its admin API.
/// No password is needed: the admin endpoint is on loopback.
pub fn write_and_reload(cfg: &Config) -> anyhow::Result<()> {
    write_config(cfg)?;
    reload()
}

pub fn reload() -> anyhow::Result<()> {
    let out = Command::new(paths::caddy_bin())
        .args(["reload", "--config"])
        .arg(paths::caddyfile())
        .args(["--address", paths::CADDY_ADMIN])
        .output()?;
    if !out.status.success() {
        anyhow::bail!(
            "caddy reload failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    Ok(())
}

/// Is the Caddy daemon up and answering on its admin API?
pub fn is_running() -> bool {
    use std::net::TcpStream;
    use std::time::Duration;
    paths::CADDY_ADMIN
        .parse()
        .ok()
        .and_then(|addr| TcpStream::connect_timeout(&addr, Duration::from_millis(400)).ok())
        .is_some()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Site;

    use crate::config::Mode;

    fn site(target: Target, ssl: bool, spa: bool) -> Site {
        Site {
            id: "mysite-test".into(),
            domain: "mysite.test".into(),
            target,
            ssl,
            spa,
            tunnel: false,
            run: false,
        }
    }

    #[test]
    fn standalone_uses_high_ports_and_binds_loopback_only() {
        let mut cfg = Config::default();
        cfg.mode = Mode::Standalone;   // stated, not inherited from the default
        cfg.sites.push(site(Target::Proxy { upstream: "127.0.0.1:8000".into() }, true, false));
        let out = render(&cfg);
        assert!(out.contains("https://mysite.test:8443 {"));
        assert!(out.contains("http_port 8080"));
        assert!(out.contains("bind 127.0.0.1"));
    }

    #[test]
    fn proxy_site_emits_tls_and_upstream() {
        let mut cfg = Config::default();
        cfg.mode = Mode::System;
        cfg.sites.push(site(Target::Proxy { upstream: "127.0.0.1:8000".into() }, true, false));
        let out = render(&cfg);
        assert!(out.contains("https://mysite.test:443 {"));
        assert!(!out.contains("http_port"));
        assert!(out.contains("tls internal"));
        assert!(out.contains(r#"reverse_proxy "127.0.0.1:8000""#));
    }

    #[test]
    fn every_site_gets_a_loopback_twin_for_tunnelling() {
        let mut cfg = Config::default();
        cfg.sites.push(site(Target::Dir { path: "/tmp".into() }, true, true));
        let out = render(&cfg);
        assert!(out.contains(&format!("http://mysite.test:{PLAIN_PORT} {{")));
        assert!(out.contains("bind 127.0.0.1"));
        assert!(out.contains("try_files {path} /index.html"));
        assert!(out.contains(r#"root * "/tmp""#));
    }

    #[test]
    fn unmatched_host_gets_an_explicit_404() {
        let mut cfg = Config::default();
        cfg.sites.push(site(Target::Proxy { upstream: "127.0.0.1:1".into() }, true, false));
        let out = render(&cfg);
        assert!(out.contains(&format!("http://:{PLAIN_PORT} {{")));
        assert!(out.contains("no site configured for {host}"));
    }

    #[test]
    fn no_sites_means_no_catch_all() {
        assert!(!render(&Config::default()).contains("no site configured"));
    }

    #[test]
    fn plain_site_omits_tls() {
        let mut cfg = Config::default();
        cfg.mode = Mode::System;
        cfg.sites.push(site(Target::Proxy { upstream: "127.0.0.1:1".into() }, false, false));
        let out = render(&cfg);
        assert!(out.contains("http://mysite.test:80 {"));
        assert!(!out.contains("tls internal"));
    }
}


#[cfg(test)]
mod security_tests {
    //! These assert on *untrusted* strings reaching two privileged sinks: the
    //! Caddyfile, which a root daemon loads, and the offline page, which is
    //! served on the user's own HTTPS origin.
    use super::*;
    use crate::config::{Config, Mode, Site};
    use crate::target::Target;

    /// Count blocks opened at column zero: the global options, the catch-all,
    /// and one pair per site. Anything more means a value escaped its context.
    fn top_level_blocks(config: &str) -> usize {
        config
            .lines()
            .filter(|l| !l.starts_with(char::is_whitespace) && l.trim_end().ends_with('{'))
            .count()
    }

    fn site_with(target: Target) -> Site {
        Site {
            id: "evil".into(),
            domain: "evil.test".into(),
            target,
            ssl: true,
            spa: false,
            tunnel: false,
            run: false,
        }
    }

    #[test]
    fn a_folder_name_cannot_break_out_of_its_caddyfile_block() {
        // A directory may legitimately contain "}" on macOS, and config.json is
        // user-writable. Either way the value must not terminate the block and
        // append directives to a root-loaded config.
        let evil = "/tmp/x}\nhttp://:9999 {\n\troot * /\n\tfile_server browse\n";
        let mut cfg = Config::default();
        cfg.mode = Mode::System;
        cfg.sites.push(site_with(Target::Dir { path: evil.into() }));

        let out = render(&cfg);
        // The payload text still appears — inside a quoted token, which is the
        // point. What must not happen is it becoming a directive of its own.
        let became_a_directive = out.lines().any(|l| l.trim() == "file_server browse");
        assert!(!became_a_directive, "injected directive reached the config:\n{out}");
        assert!(out.contains("root * \""), "the path was not quoted:\n{out}");
        // Structural check: exactly the blocks we intended, and no more.
        // (The payload text survives inside the quoted path, which is inert.)
        assert_eq!(top_level_blocks(&out), 4, "extra blocks appeared:\n{out}");
    }

    #[test]
    fn a_php_root_cannot_break_out_either() {
        let evil = "/tmp/y}\nhttp://:9998 {\n\trespond \"owned\"\n";
        let mut cfg = Config::default();
        cfg.mode = Mode::System;
        cfg.sites.push(site_with(Target::Php { root: evil.into() }));
        let out = render(&cfg);
        assert!(!out.lines().any(|l| l.trim().starts_with("respond \"owned\"")));
        assert_eq!(top_level_blocks(&out), 4, "extra blocks appeared:\n{out}");
    }

    #[test]
    fn an_upstream_cannot_inject_directives() {
        let evil = "127.0.0.1:1\n\trespond \"owned\"";
        let mut cfg = Config::default();
        cfg.mode = Mode::System;
        cfg.sites.push(site_with(Target::Proxy { upstream: evil.into() }));
        let out = render(&cfg);
        assert!(!out.lines().any(|l| l.trim().starts_with("respond \"owned\"")));
    }

    #[test]
    fn the_offline_page_escapes_what_it_interpolates() {
        // This page is served from https://<site>, so script injected here runs
        // on that origin with access to its storage.
        let evil = "/tmp/<script>alert(1)</script>";
        let site = site_with(Target::Node {
            dir: evil.into(),
            command: "npm run \"><script>alert(2)</script>".into(),
            port: 3000,
        });
        let html = offline_html(&site);
        assert!(!html.contains("<script>alert(1)</script>"), "unescaped dir:\n{html}");
        assert!(!html.contains("<script>alert(2)</script>"), "unescaped command:\n{html}");
    }

    #[test]
    fn the_offline_page_title_attribute_cannot_be_escaped() {
        let site = site_with(Target::Node {
            dir: "/tmp/a\" onmouseover=alert(1) x=\"".into(),
            command: "npm run dev".into(),
            port: 3000,
        });
        let html = offline_html(&site);
        // Again the text survives; what matters is that it cannot close the
        // attribute and become markup.
        assert!(!html.contains("\" onmouseover"), "attribute was broken out of:\n{html}");
        assert!(html.contains("&quot;"), "the quote was not escaped:\n{html}");
    }
}
