use crate::config::{Site, PLAIN_PORT};
use serde::Serialize;
use std::collections::HashMap;
use std::io::{BufRead, BufReader};
use std::process::{Child, Command, Stdio};
use std::sync::{Arc, Mutex, OnceLock};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum TunnelStatus {
    Stopped,
    Starting,
    Running,
    Failed,
}

#[derive(Debug, Clone, Serialize)]
pub struct TunnelInfo {
    pub status: TunnelStatus,
    pub url: Option<String>,
    pub error: Option<String>,
}

impl TunnelInfo {
    fn stopped() -> Self {
        TunnelInfo { status: TunnelStatus::Stopped, url: None, error: None }
    }
}

struct Handle {
    child: Child,
    info: Arc<Mutex<TunnelInfo>>,
}

fn registry() -> &'static Mutex<HashMap<String, Handle>> {
    static REG: OnceLock<Mutex<HashMap<String, Handle>>> = OnceLock::new();
    REG.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Locate cloudflared, preferring a copy the user manages themselves.
///
/// Their own install stays authoritative — if they have it from Homebrew we
/// use that and let brew keep it updated, rather than shadowing it with ours.
pub fn cloudflared_bin() -> Option<String> {
    let mut candidates: Vec<String> = vec![
        "/opt/homebrew/bin/cloudflared".to_string(),
        "/usr/local/bin/cloudflared".to_string(),
    ];
    candidates.push(crate::paths::managed_cloudflared().to_string_lossy().into_owned());

    candidates
        .into_iter()
        .find(|p| std::path::Path::new(p).exists())
}

pub fn is_installed() -> bool {
    cloudflared_bin().is_some()
}

/// Fetch cloudflared if it is not already present.
///
/// Public tunnels need no Cloudflare account — a quick tunnel is anonymous —
/// but they do need this binary, and asking a user to run `brew install` first
/// is exactly the manual step this app exists to remove.
///
/// The download comes over HTTPS from Cloudflare's official GitHub release, is
/// unpacked into our own directory, and is then required to run and report a
/// version before we will use it.
pub fn ensure_cloudflared() -> anyhow::Result<String> {
    if let Some(found) = cloudflared_bin() {
        return Ok(found);
    }
    install_cloudflared()
}

/// Download cloudflared into our own directory, whether or not one is already
/// present elsewhere.
pub fn install_cloudflared() -> anyhow::Result<String> {
    let status = crate::bins::ensure_cloudflared_reporting(true, &crate::bins::no_progress)?;
    status
        .path
        .ok_or_else(|| anyhow::anyhow!("cloudflared did not install"))
}

pub fn extract_url(line: &str) -> Option<String> {
    let idx = line.find("https://")?;
    let rest = &line[idx..];
    let end = rest
        .find(|c: char| c.is_whitespace() || c == '|' || c == '"')
        .unwrap_or(rest.len());
    let url = rest[..end].trim_end_matches(['.', ',']).to_string();
    if url.contains("trycloudflare.com") {
        Some(url)
    } else {
        None
    }
}

/// Quote a value for the generated cloudflared config.
///
/// Same reasoning as the Caddyfile: this is a config file assembled from
/// values that reached us from outside, and an unquoted one could end the
/// mapping and start a directive of its own. Hostnames are validated before
/// they get here; this is the second lock on the same door.
fn yaml_quote(value: &str) -> String {
    let cleaned: String = value.chars().filter(|c| !c.is_control()).collect();
    format!("\"{}\"", cleaned.replace('\\', "\\\\").replace('"', "\\\""))
}

/// Write the credentials and ingress rules a named tunnel runs from.
///
/// Ingress points at the same loopback twin a quick tunnel uses, with the
/// site's real hostname forced into the Host header — so a request arriving
/// on the public name lands on precisely the handler a local one would.
fn write_named_config(site: &Site, tunnel: &crate::cloudflare::Tunnel, account_id: &str, hostname: &str) -> anyhow::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    crate::paths::ensure_dirs()?;

    let creds = crate::paths::tunnel_credentials(&site.id);
    let body = serde_json::json!({
        "AccountTag": account_id,
        "TunnelID": tunnel.id,
        "TunnelSecret": tunnel.secret,
    });
    std::fs::write(&creds, serde_json::to_string(&body)?)?;
    // The secret in here is the right to serve traffic on the user's own
    // hostname. Nothing but this account may read it.
    std::fs::set_permissions(&creds, std::fs::Permissions::from_mode(0o600))?;

    let yml = format!(
        "# Generated by Portico. Edits here are overwritten.\n\
         tunnel: {}\n\
         credentials-file: {}\n\
         ingress:\n\
         \x20 - hostname: {}\n\
         \x20   service: http://127.0.0.1:{PLAIN_PORT}\n\
         \x20   originRequest:\n\
         \x20     httpHostHeader: {}\n\
         \x20 - service: http_status:404\n",
        yaml_quote(&tunnel.id),
        yaml_quote(&creds.to_string_lossy()),
        yaml_quote(hostname),
        yaml_quote(&site.domain),
    );
    std::fs::write(crate::paths::tunnel_config(&site.id), yml)?;
    Ok(())
}

/// Claim the Cloudflare-side resources a named tunnel needs, and return its id.
///
/// Creates the tunnel if it does not exist, writes the local config, then
/// points DNS at it. Ordering is deliberate: DNS goes last, so a name only
/// starts resolving once there is something behind it to answer.
///
/// Returns `None` when this site does not want a named tunnel, which leaves
/// the caller on the anonymous quick-tunnel path.
pub fn provision(site: &Site) -> anyhow::Result<Option<String>> {
    let cfg = crate::config::Config::load();
    if cfg.tunnel_provider != crate::ngrok::Provider::Cloudflare {
        return Ok(None);
    }
    let Some(hostname) = site.public_hostname() else {
        return Ok(None);
    };

    let token = crate::secrets::get(crate::secrets::CLOUDFLARE_TOKEN).ok_or_else(|| {
        anyhow::anyhow!(
            "{hostname} needs a Cloudflare API token — add one in Settings, or clear the hostname to use a temporary URL"
        )
    })?;

    let account = match cfg.cloudflare_account.clone() {
        Some(id) => id,
        None => crate::cloudflare::verify(&token)?.id,
    };
    let zones = crate::cloudflare::zones(&token)?;
    let zone = crate::cloudflare::zone_for(&zones, hostname).ok_or_else(|| {
        anyhow::anyhow!("{hostname} is not inside any domain on this Cloudflare account")
    })?;

    // Reuse the tunnel already backing this site where we can. Creating a
    // second one for the same site would orphan the first, and Cloudflare
    // would keep billing attention for a tunnel nothing runs.
    let name = format!("portico-{}", site.id);
    let existing = match &site.tunnel_id {
        Some(id) => Some(id.clone()),
        None => crate::cloudflare::find_tunnel(&token, &account, &name)?,
    };

    let tunnel = match existing {
        // The secret is only ever returned at creation, so a tunnel we are
        // adopting must be replaced to be runnable. Deleting first keeps the
        // name free for the one we are about to make.
        Some(id) if !crate::paths::tunnel_credentials(&site.id).exists() => {
            let _ = crate::cloudflare::delete_tunnel(&token, &account, &id);
            crate::cloudflare::create_tunnel(&token, &account, &name)?
        }
        Some(id) => crate::cloudflare::Tunnel {
            id,
            name: name.clone(),
            // Already on disk from a previous run; the config file below is
            // rewritten from it rather than from this placeholder.
            secret: String::new(),
        },
        None => crate::cloudflare::create_tunnel(&token, &account, &name)?,
    };

    if tunnel.secret.is_empty() {
        // Adopting an existing local credentials file: only the ingress rules
        // need refreshing, in case the hostname or site domain changed.
        rewrite_ingress(site, &tunnel.id, hostname)?;
    } else {
        write_named_config(site, &tunnel, &account, hostname)?;
    }

    crate::cloudflare::upsert_dns(&token, &zone.id, hostname, &tunnel.id)?;
    Ok(Some(tunnel.id))
}

/// Refresh only the ingress rules, keeping credentials already on disk.
fn rewrite_ingress(site: &Site, tunnel_id: &str, hostname: &str) -> anyhow::Result<()> {
    let creds = crate::paths::tunnel_credentials(&site.id);
    let yml = format!(
        "# Generated by Portico. Edits here are overwritten.\n\
         tunnel: {}\n\
         credentials-file: {}\n\
         ingress:\n\
         \x20 - hostname: {}\n\
         \x20   service: http://127.0.0.1:{PLAIN_PORT}\n\
         \x20   originRequest:\n\
         \x20     httpHostHeader: {}\n\
         \x20 - service: http_status:404\n",
        yaml_quote(tunnel_id),
        yaml_quote(&creds.to_string_lossy()),
        yaml_quote(hostname),
        yaml_quote(&site.domain),
    );
    std::fs::write(crate::paths::tunnel_config(&site.id), yml)?;
    Ok(())
}

/// Give back a site's named tunnel and its DNS record.
///
/// Best effort by design: this runs while a site is being deleted, and a
/// network blip must not block that. Anything left behind is visible in the
/// Cloudflare dashboard under the `portico-` prefix.
pub fn deprovision(site: &Site) {
    let Some(tunnel_id) = site.tunnel_id.clone() else { return };
    let cfg = crate::config::Config::load();
    let Some(token) = crate::secrets::get(crate::secrets::CLOUDFLARE_TOKEN) else { return };
    let Some(account) = cfg.cloudflare_account.clone() else { return };

    if let Some(hostname) = site.public_hostname() {
        if let Ok(zones) = crate::cloudflare::zones(&token) {
            if let Some(zone) = crate::cloudflare::zone_for(&zones, hostname) {
                let _ = crate::cloudflare::delete_dns(&token, &zone.id, hostname);
            }
        }
    }
    let _ = crate::cloudflare::delete_tunnel(&token, &account, &tunnel_id);
    let _ = std::fs::remove_file(crate::paths::tunnel_credentials(&site.id));
    let _ = std::fs::remove_file(crate::paths::tunnel_config(&site.id));
}

/// Whether a cloudflared line says the agent reached Cloudflare's edge.
///
/// For a named tunnel this, not a URL, is the moment the hostname starts
/// answering — the address was decided when DNS was written.
pub fn connection_registered(line: &str) -> bool {
    line.contains("Registered tunnel connection")
}

/// Start a public tunnel for one site.
///
/// cloudflared is pointed at the loopback plain-HTTP twin rather than the
/// HTTPS vhost, so it never needs to trust the local CA; `--http-host-header`
/// makes the request arrive at Caddy under the site's real hostname.
///
/// A named tunnel is different in one useful way: its URL is decided before
/// the process starts, so there is nothing to scrape out of the log and the
/// UI can show the address immediately.
pub fn start(site: &Site) -> anyhow::Result<()> {
    stop(&site.id);

    let cfg = crate::config::Config::load();
    let provider = cfg.tunnel_provider;
    let domain = site.domain.as_str();
    let named = (provider == crate::ngrok::Provider::Cloudflare)
        .then(|| site.public_hostname())
        .flatten();

    // Kept so it can be scrubbed out of anything the agent prints — a rejected
    // token is quoted back in ngrok's own error text.
    let ngrok_token = (provider == crate::ngrok::Provider::Ngrok)
        .then(crate::ngrok::authtoken)
        .flatten();

    // Each provider needs a different binary, different arguments and a
    // different way of finding the URL in its output.
    let (bin, args, known_url) = match (provider, named) {
        (crate::ngrok::Provider::Cloudflare, Some(host)) => {
            let bin = ensure_cloudflared()?;
            let config = crate::paths::tunnel_config(&site.id);
            if !config.exists() {
                anyhow::bail!("The tunnel for {host} is not set up yet");
            }
            let args = vec![
                "tunnel".to_string(),
                "--no-autoupdate".to_string(),
                "--config".to_string(),
                config.to_string_lossy().into_owned(),
                "run".to_string(),
            ];
            (bin, args, Some(format!("https://{host}")))
        }
        (crate::ngrok::Provider::Cloudflare, None) => {
            // Fetches it on first use if needed, so turning a site public never
            // depends on the user having installed anything.
            let bin = ensure_cloudflared()?;
            let args = vec![
                "tunnel".to_string(),
                "--no-autoupdate".to_string(),
                "--url".to_string(),
                format!("http://127.0.0.1:{PLAIN_PORT}"),
                "--http-host-header".to_string(),
                domain.to_string(),
            ];
            (bin, args, None)
        }
        (crate::ngrok::Provider::Ngrok, _) => {
            let bin = crate::ngrok::bin()
                .ok_or_else(|| anyhow::anyhow!("ngrok is not installed"))?;
            let status = crate::ngrok::status(cfg.ngrok_plan.as_deref());
            if !status.configured {
                anyhow::bail!(
                    "ngrok has no authtoken. Add one in Settings — ngrok requires an account."
                );
            }
            let mut args = crate::ngrok::config_args();
            args.extend(crate::ngrok::tunnel_args(PLAIN_PORT, domain, site.public_hostname()));
            (bin, args, None)
        }
    };

    let site_id = site.id.as_str();

    let info = Arc::new(Mutex::new(TunnelInfo {
        status: TunnelStatus::Starting,
        url: known_url.clone(),
        error: None,
    }));

    let mut child = Command::new(bin)
        .args(&args)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()?;

    // cloudflared logs the URL on stderr; ngrok on stdout. Read both so the
    // provider does not have to be special-cased twice.
    let streams: Vec<Box<dyn std::io::Read + Send>> = vec![
        Box::new(child.stderr.take().expect("stderr piped")),
        Box::new(child.stdout.take().expect("stdout piped")),
    ];

    let log_path = crate::paths::tunnel_log(site_id);
    let _ = crate::paths::ensure_dirs();
    let log = Arc::new(Mutex::new(std::fs::File::create(&log_path).ok()));

    for stream in streams {
        let info = Arc::clone(&info);
        let log = Arc::clone(&log);
        let log_path = log_path.clone();
        let is_named = known_url.is_some();
        let secret = ngrok_token.clone();
        std::thread::spawn(move || {
            let mut tail: Vec<String> = Vec::new();
            for line in BufReader::new(stream).lines().map_while(Result::ok) {
                // Scrub before the line reaches the log file or the tail we
                // surface as an error. ngrok echoes a rejected authtoken.
                let line = crate::ngrok::redact(&line, secret.as_deref());
                if let Ok(mut f) = log.lock() {
                    if let Some(f) = f.as_mut() {
                        use std::io::Write;
                        let _ = writeln!(f, "{line}");
                    }
                }

                // A named tunnel already knows its address; what it is waiting
                // for is a connection to the edge, which is what actually
                // makes the hostname answer.
                if is_named {
                    if connection_registered(&line) {
                        let mut i = info.lock().unwrap();
                        i.status = TunnelStatus::Running;
                    }
                } else {
                    let found = match provider {
                        crate::ngrok::Provider::Cloudflare => extract_url(&line),
                        crate::ngrok::Provider::Ngrok => crate::ngrok::extract_url(&line),
                    };
                    if let Some(url) = found {
                        let mut i = info.lock().unwrap();
                        i.url = Some(url);
                        i.status = TunnelStatus::Running;
                        continue;
                    }
                }

                tail.push(line);
                if tail.len() > 40 {
                    tail.remove(0);
                }
            }

            // Stream closed. Only the first one to notice reports a failure.
            let mut i = info.lock().unwrap();
            if i.status == TunnelStatus::Starting {
                i.status = TunnelStatus::Failed;
                i.error = Some(
                    tail.iter()
                        .rev()
                        .find(|l| l.contains("ERR_NGROK") || l.contains("ERR") || l.contains("error"))
                        .cloned()
                        .unwrap_or_else(|| {
                            format!("Tunnel exited before publishing a URL — see {}", log_path.display())
                        }),
                );
            }
        });
    }

    registry()
        .lock()
        .unwrap()
        .insert(site_id.to_string(), Handle { child, info });
    Ok(())
}

pub fn stop(site_id: &str) {
    if let Some(mut h) = registry().lock().unwrap().remove(site_id) {
        let _ = h.child.kill();
        let _ = h.child.wait();
    }
}

pub fn stop_all() {
    let ids: Vec<String> = registry().lock().unwrap().keys().cloned().collect();
    for id in ids {
        stop(&id);
    }
}

pub fn status(site_id: &str) -> TunnelInfo {
    registry()
        .lock()
        .unwrap()
        .get(site_id)
        .map(|h| h.info.lock().unwrap().clone())
        .unwrap_or_else(TunnelInfo::stopped)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn finds_quick_tunnel_url() {
        let line = "2026-09-08T10:00:00Z INF |  https://brave-lion-runs-fast.trycloudflare.com   |";
        assert_eq!(
            extract_url(line).as_deref(),
            Some("https://brave-lion-runs-fast.trycloudflare.com")
        );
    }

    #[test]
    fn ignores_other_urls() {
        assert!(extract_url("see https://developers.cloudflare.com/docs for help").is_none());
        assert!(extract_url("no url at all").is_none());
    }

    #[test]
    fn unknown_site_reports_stopped() {
        assert_eq!(status("nope").status, TunnelStatus::Stopped);
    }

    #[test]
    fn a_named_tunnel_is_running_only_once_it_reaches_the_edge() {
        // The hostname is decided when DNS is written, so the log gives no
        // URL to wait for. A registered connection is the real signal.
        assert!(connection_registered(
            "2026-09-09T10:00:00Z INF Registered tunnel connection connIndex=0"
        ));
        assert!(!connection_registered("2026-09-09T10:00:00Z INF Starting tunnel"));
    }

    #[test]
    fn config_values_cannot_break_out_of_the_yaml() {
        // Same sink as the Caddyfile: a generated config file assembled from
        // values that came from outside. An unquoted one would end the
        // mapping and start a directive of its own.
        assert_eq!(yaml_quote("hooks.example.com"), "\"hooks.example.com\"");
        assert_eq!(yaml_quote("a\"b"), "\"a\\\"b\"");
        assert_eq!(yaml_quote("a\\b"), "\"a\\\\b\"");
        // Control characters are dropped, not escaped — nothing legitimate
        // has them, and keeping them only gives an attacker material.
        assert_eq!(yaml_quote("a\nb"), "\"ab\"");
        assert_eq!(yaml_quote("a\rb"), "\"ab\"");
    }
}
