[package]
name = "portico-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "portico-app"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
portico-core.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tauri = { version = "2", features = ["tray-icon", "image-png"] }
